# This workflow will run when a commit message to master begins with "Release ". The
# message should include the current version number, which will be set as a new
# tag's name and message. Example message: "Release 1.1.0"

name: npm-publish
on:
  push:
    branches:
      - master # Change this to your default branch
jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 10.19
    - name: Install dependencies (all)
      run: npm install
    - name: Add safe repository
      run: git config --global --add safe.directory /github/workspace
    - name: Publish if commit message matches release pattern
      uses: mkiki/npm-publish-action@c4315ef5790b7bcec2cbb75b34e37681a409d78d
      with:
        tag_name: "v%s"
        tag_message: "v%s"
        commit_pattern: "^Release (\\S+)"
        workspace: "."
      env: # More info about the environment variables in the README
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this as is, it's automatically generated
        NPM_AUTH_TOKEN: ${{ secrets.ADOBE_BOT_NPM_TOKEN }} # This will be shared with your repo as an org secret
        NPM_AUTH: ${{ secrets.ADOBE_BOT_NPM_TOKEN }} # This will be shared with your repo as an org secret
